
name: Build code, run unit test, run SAST, SCA, DAST security scans
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  # Manual trigger from the UI
  workflow_dispatch:

jobs:

  zap_scan:
    runs-on: ubuntu-latest
    name: Run DAST scan on the web application
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main
      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.6.1
        with:
          docker_name: 'owasp/zap2docker-stable'
          target: 'http://testphp.vulnweb.com/'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'
