name: Check run

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  # Manual trigger from the UI
  workflow_dispatch:

jobs:
  check-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - run: sudo apt-get update && sudo apt-get install -y nginx && sudo systemctl start nginx

    - name: ZAP Scan
      uses: ./
      id: action-full-scan
      with:
        target: 'http://localhost'
        allow_issue_writing: false
